### ISSUE TITLE
Support Maven's directory structure

### ISSUE THREAD

**Issue by kingargyle** [Killerardvark/CryodexSource#13]
Maven has promoted a standard format for the locations of source files, tests, generated-sources, and other artifacts.  This allows tooling to consistently know where items are located.

I'm looking at adding to the maven build the ability to package a zip file that contains all items necessary for a user to use to get up and running with Cryodex.   This includes BAT and shell scripts, and the latest JAR file for cryodex.

I can configure the build to use the non-standard directories now, or I could submit a pull request that does some restructring.    Ideally, the restructuring work could include breaking out the Imperial Assault, Armada, and X-Wing items into their own modules.  We could then include them as seperate jars, or we can re-combine them all into one jar for distribution.   

The seperate modules as their own jars is work that can be done later and doesn't need to occur during the initial restructring.

The long term goal is to get the project to the point where the maven release plugin can be used to help do a formal release, increment project version numbers, package the final zip file, and then upload and update the Github page with release notes, and a link to the latest binary ready for people to use.

Ideally somebody should be able to grab a ZIP, and just click on one of the bar or shell scripts and get running if they have Java installed already.   I had to help another person this weekend get things running because they weren't as technical about java and the command line.

**Comment by kingargyle** [comment]
Some information on how to leverage the Github Releases feature.

https://github.com/blog/1547-release-your-software

**Comment by Killerardvark** [comment]
I believe you already completed this task. Please reopen if not.
