### ISSUE TITLE
Modification Needed For Adding Players To Tournament

### ISSUE THREAD

**Issue by Killerardvark** [Killerardvark/CryodexSource#15]
User rgeer3 on BGG would like a mechanism for adding players to a tournament that makes it easy for TOs who have accumulated players over the course of a few events.

Example: He has a running total of players who have played in events. When he gets to the screen to add players, he has to have a list of players in this event to know who to add. He would like a simple way to either add the correct players quickly or add mark them as "in next event" when adding them on the registration screen.

**Comment by Killerardvark** [comment]
Additional comments from rgeer3:

I had a suggestion for your program (couple of us are thinking the same thing); on the Main Screen (where you add names), adding some way to A-Z the list (the Event Wizard does this, but only so after you have added one player)? 

It can get tedious keeping track of names, and I had suggested a variation of this, but thought of a better one. From the Main Screen when adding a players name to list (or selecting one already in the system), make a ADD To Event tab, then when you Open the Event Wizard Tab, the only players names loaded are the ones you previously added to the "Event".

**Comment by CoreyAFraser** [comment]
@Killerardvark I submitted a pull request yesterday for searching/filtering the list of players on this screen. I looked through the list of issues afterward and realized that my pull request may resolve this issue, although in a different manner.
Though, it is possible that I'm misunderstanding this issue.

**Comment by Killerardvark** [comment]
Searching helps a bit. I'll try to explain the core issue. As a TO you have people register at the beginning of the event. Then when everyone is registered you go to create the event. Adding players to the event can feel like reregistering everyone because you have to go back through your list (assuming your player list is filled with players from previous events). Instead I would like to add a checkbox of "add to next event" or something similar. Then on the wizard page where you select players you can press one button that adds all of those players.

**Comment by CoreyAFraser** [comment]
Ok, I think I might have some time to handle this later in the week or over the weekend.
