### ISSUE TITLE
Tiebreakers on with duplicate matches

### ISSUE THREAD

**Issue by fortyeightkb** [Killerardvark/CryodexSource#2]
On a tournament we run, we had a duplicate match. So Player A and Player B played twice with each other. And in the 1 game player A won, on the 2 game Player B won. On the end of the tournament, player B had a better MOV, but the player A only appears on top on the player rankings window.
On all the exports the player B appears on the top.

Another problem we had on this tournament is, that in all exports the player B appears twice. Once before player A and a second time after player B.

If you need more info (full report for the tournament) just let me know.

**Comment by Killerardvark** [comment]
Can you send me the tournament report and the Cryodex.save file? Send to Chris.brown.spe@gmail.com

Also, can you explain why you allowed a duplicate match to happen in your tournament? Rules state that players should not play twice unless the second time is in single elimination.

**Comment by Killerardvark** [comment]
This is fixed and will be out in the next release.
