### ISSUE TITLE
Cryodex 4.1.2 does not load Cryodex.save correctly

### ISSUE THREAD

**Issue by miviks** [Killerardvark/CryodexSource#21]
Verified that 4.1.1 loads Cryodex.save correctly, but 4.1.2 will open blank and then save a blank Cryodex.save on exit.

**Comment by Killerardvark** [comment]
Thanks for verifying. I'll check it out when I get home. Like you said though. I can't imagine why it would be doing that.

Couple questions:

What kind of operating system are you on?
How do you typically open cryodex?
On 4.1.1 and 4.1.2 can you select the option that shows you where your save file is just to see what it says.

**Comment by miviks** [comment]
On Windows 7 (work) or Windows 10 (home).
Usually just open the .jar by standard doubleclick and let os launch java.

4.1.1 - A save file could not be found. It should be called XWingTournament.save and should be located in folder C:\Uses\mikael\Google Drive\Spel\X-Wing\Starfighters

4.1.2 - A save file could not be found. It should be called XWingTournament.save and should be located in folder C:\Uses\mikael\Google Drive\Spel\X-Wing\Starfighters

This is just getting wierder.

**Comment by Killerardvark** [comment]
Yeah, I was able to test it here at work. First, that save file find function is obviously looking for the old filename. My fault, that needs to be fixed. One the bright side, it's looking in the right folder, so hurray? I'll figure it out when I get home or revert back to 4.1.1. My laptop had a meltdown  this past weekend and my Eclipse runtime got all messed up. I'm wondering if something in the build settings got wacky. I'll figure it out.

**Comment by Killerardvark** [comment]
Problem fixed. I forgot to set the menu option as checked when I set the view option as true. Having those operate seperately is really not good in hindsight. Need to figure out a better solution. Anyways, it was triggering a save before the load could flip the "do not save while loading" flag. Fixed now as well as the help that shows where the save file is.
