### ISSUE TITLE
"Unprotected" Warning

### ISSUE THREAD

**Issue by Killerardvark** [Killerardvark/CryodexSource#26]
There should be some sort of indicator on the main screen that is really obvious and obnoxious when you're running in a mode that is preventing the save function from working.

**Comment by Killerardvark** [comment]
Warning message will be in next build. Most likely 4.2.0

**Comment by miviks** [comment]
I get the warning message popping constantly, even when the save functionality seem to be working fine.

**Comment by Killerardvark** [comment]
problem fixed, the program encounters some random errors when saving due to too many things happening at once and it is trying to save too quick since the last save. Yeah, I save pretty much constantly. This caused an error in saving because the lock hadn't been released on the file since the last save. I've not modified it to remove the message if a successful save happens. Completely untested, but hey, whatever, we'll see what happens.
