### ISSUE TITLE
Armada: concession implementation

### ISSUE THREAD

**Issue by nexusno2000** [Killerardvark/CryodexSource#42]
Hi,

The current concession implementation for Armada isn't in accordance with the tourney regs.

If a player concedes, the score is auto 8-0 MoV 140 to his opponent.

This, however, is not correct.

If the score, at the time of the concession, is greater than 8 MoV 140 (for example 9 MoV 200), that's the number of points awarded to the winner. The conceding party still gets 0 oc.

So if a Concession could just give 0 to the conceding party, but the winner gets tourney pts and MoV as entered into the results block, that would be great.

**Comment by Killerardvark** [comment]
This should be correct in any 5.0.0+ build.

**Comment by nexusno2000** [comment]
Excellent, thank you.

Bjørn

2017-10-16 15:10 GMT+02:00 Christopher Brown <notifications@github.com>:
