### ISSUE TITLE
Destiny: Export Matches

### ISSUE THREAD

**Issue by Tappiocca** [Killerardvark/CryodexSource#49]
In Destiny, there is no option to Export Match Slips. Seems all the other games have this option open to them.

**Comment by Killerardvark** [comment]
You can't do it for imperial assault either. That's what I copied it off of. Should be easy enough to do, but I'm stuck in a larger change at the moment. I'll try to remember it as I go. Thanks for the report!

**Comment by Killerardvark** [comment]
This should be fixed in any version 5.0.0+ let me know if you are still having issues.
