### ISSUE TITLE
Add option to cut to top 2

### ISSUE THREAD

**Issue by Killerardvark** [Killerardvark/CryodexSource#5]
Request submitted by Mu0n. A cut to top 2 doesn't add any functionality for tournament operation, but does allow for a complete tournament report as well as uploading results to ListJuggler. Adding this option should be trivial.

**Comment by Killerardvark** [comment]
This is done and will be in the next jar version uploaded later today.

**Comment by kingargyle** [comment]
One thing that would be nice, is that when a bug is fixed, is that in the comment you could reference the Issue number it corresponds too.   Github will then automatically link that commit or set of commits to the issue number.

**Comment by kingargyle** [comment]
See https://github.com/blog/957-introducing-issue-mentions for more information.
