### ISSUE TITLE
Cryodex closing immediately upon opening.

### ISSUE THREAD

**Issue by MyArtificialLife** [Killerardvark/CryodexSource#53]
I have Java installed but when I opened Cryodex I see the Command Prompt window open momentarily then close again.  Nothing happens after that.

**Comment by Killerardvark** [comment]
It's working on my machine. My guess is that you have an issue with your Java runtime environment. Try holding shift and right clicking on the folder. An option should appear to open a command prompt, or powershell if you're on windows 10. Then execute the file from there. The command is "java -jar Cryodex.jar". Then if there is an error right up front the command prompt will now disappear and you'll be able to see what it is.

You're also welcome to message me directly on facebook. My name is Chris 'Chico' Brown.

**Comment by MyArtificialLife** [comment]
It tells me it's unable to access Cryodex.jar.  I'm sure it's something wrong with the Java I have installed.  I have to go through my company admin and they install everything.

**Comment by Killerardvark** [comment]
Sounds like you are trying to execute the application in a folder that java does not have run capabilities. That makes sense if your company has machines on super lockdown.
