### ISSUE TITLE
hi issue 5.04 vs 4.74

### ISSUE THREAD

**Issue by sirmaugan** [Killerardvark/CryodexSource#54]
i have organised a Destiny tournament and the results from 5.04 version isn't the same whith the 4.74
i think the 4.74 is the good results

![14 10 4 7 4](https://user-images.githubusercontent.com/27279227/31585823-91635976-b1c8-11e7-9949-0f4de4c738a1.jpg)
![14 10 5 04](https://user-images.githubusercontent.com/27279227/31585824-917c6132-b1c8-11e7-94ca-b1a1334b8c21.jpg)

**Comment by Killerardvark** [comment]
Which one is which?

**Comment by Killerardvark** [comment]
I figured it out. I'll be posting the update soon. Thanks for the report!

**Comment by Killerardvark** [comment]
Fix submitted in 5.0.5. Give it a look and let me know what you think. Note, the decimal values in Ext SoS are slightly different, but the ranking should be correct.

**Comment by sirmaugan** [comment]
thanks whith the same .sav e file the ranking is good this time !
