### ISSUE TITLE
Import/Export interfaces

### ISSUE THREAD

**Issue by althaus** [Killerardvark/CryodexSource#6]
Hi,

I'm running the tournament organization page [T³ - TabletopTournament.net](http://www.tabletoptournaments.net) with quite an active European X-Wing community and one of my users asked, if it'd be possible to support our data formats in your software. We've got the possibility to export the registrations of an event to a custom format and import the results in a custom format or as XML.

For us it'd be important to track custom player data like our UserID. A quick look showed the possiblity for a custom exporter. That's great, but what about import?

Best regards
Matthias aka Blackhawk on T³

**Comment by Killerardvark** [comment]
Thanks for the comments Matthias. I've wanted to do custom importers for a while but haven't gotten around to it. It is definitely a goal for my Jan 1 release. I'm open to a dialog about the best way to do this though.

Here's what I'm thinking. Some sort of mapping classes that convert the importing file into something I can work with easily. Not sure if the best way would be the standard POJO objects at this point or if it should be more of a raw wrapper class that can then be converted to the POJOs on my side of the fence. These mapping classes could then be written by anyone wanting to import a file. That way people don't have to deal with exporting to a particular format from their application unless they want to conform to a format already supported. Hopefully we can find a way to automatically detect the type of file to push it to the correct converter.

Thoughts anyone? I'll get to this eventually, but if anyone wants to jump on it I'm open to help.

**Comment by Killerardvark** [comment]
Matthias,
Could you upload an example version of our current output?

**Comment by althaus** [comment]
I've put all the formats we've got in this Gist:

https://gist.github.com/althaus/33aeb0938ff4640361ab

I must admit the formats have grown over 10+ years and therefore are quite chaotic. It'd be no problem to unify all the parameters and so on. Some values llike armylist rating or fairplay points are specific for our [pairing software](https://www.tabletoptournaments.net/goepp) which was made for classic Warhammer.

Absolute awesome would be a "standarized" tournament exchange format (in JSON/XML?).

Cheers
Matthias

**Comment by althaus** [comment]
>These mapping classes could then be written by anyone wanting to import a filebtw: 
That would be the easiest solution I guess. It's just important to get the data back you've imported. :)
