### ISSUE TITLE
Travis CI Build for Cryodex

### ISSUE THREAD

**Issue by kingargyle** [Killerardvark/CryodexSource#8]
One of the things that would be nice is to have automated builds and verification for when problems are fixed with Cryodex.   Many github projects leverage Travis CI which is free for open source software projects.

https://travis-ci.org/getting_started

Also, it would be nice to start having some unit tests around the code.   In general it will give that additional layer of confidence that a bug is fixed.

**Comment by Killerardvark** [comment]
I'll look into the automated build process, but it is unlikely that I will use it. I like to have better control over when a build is released. I don't want a checkin to instantly result in a new build.

Some unit tests may be nice to have. Much of this program involves the GUI and those aren't very conducive to unit tests. For more behind the scenes functions, people are welcome to write tests, but I most likely will not be writing any. Not that I don't see the value, I just don't see it happening any time soon.

**Comment by kingargyle** [comment]
You don't have to release the builds, they are mainly there for verification. You control when you actually release a product.   The check in results for builds are mainly there to verify other people's contributions.  Not to release an actual product to the public, you still control that.

**Comment by kingargyle** [comment]
The one thing I would like to see from Cryodex is a little more seperation of the UI parts from the business logic.  It would make it easier to eventually add a Web Frontend and re-use the core of cryodex in a league management software extension.
